service: ez-az
image: jaykilleen/ez-az

servers:
  web:
    hosts:
      - 172.105.171.81

proxy:
  ssl: true
  host: ez-az.net
  app_port: 3000
  healthcheck:
    path: /up
    interval: 3
    timeout: 10

registry:
  server: ghcr.io
  username: jaykilleen
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    RAILS_LOG_LEVEL: info
    RAILS_SERVE_STATIC_FILES: "true"
    PORT: "3000"
  secret:
    - SECRET_KEY_BASE
    - HONEYBADGER_API_KEY
    - ADMIN_PASSWORD
    - SENDGRID_API_KEY

builder:
  arch: amd64
  context: "."

ssh:
  user: root

volumes:
  - ez_az_storage:/rails/storage
